### ISSUE TITLE
Illegal argument exception when initial route conatins all jobs

### ISSUE THREAD

**Issue by muzuro** [jsprit/jsprit#177]
When all jobs is contained in initial route search solutions fails with:
```
java.lang.IllegalArgumentException: bound must be positive
        at java.util.Random.nextInt(Random.java:388)
        at jsprit.core.util.RandomUtils.nextItem(RandomUtils.java:28)
        at jsprit.core.util.RandomUtils.nextJob(RandomUtils.java:20)
        at jsprit.core.algorithm.ruin.RuinClusters.ruin(RuinClusters.java:130)
        at jsprit.core.algorithm.ruin.RuinClusters.ruinRoutes(RuinClusters.java:106)
        at jsprit.core.algorithm.ruin.AbstractRuinStrategy.ruin(AbstractRuinStrategy.java:65)
        at jsprit.core.algorithm.module.RuinAndRecreateModule.runAndGetSolution(RuinAndRecreateModule.java:50)
        at jsprit.core.algorithm.SearchStrategy.run(SearchStrategy.java:144)
        at jsprit.core.algorithm.VehicleRoutingAlgorithm.searchSolutions(VehicleRoutingAlgorithm.java:204)
```
I am using v1.6.1.

**Comment by muzuro** [comment]
jsprit.core.problem.VehicleRoutingProblem.getJobs() returns empty collection.

**Comment by oblonski** [comment]
Thanks for reporting :+1: . Will fix this asap.
